// Bake the package version into src/version.ts before tsc, so the runtime update-check has it in EVERY
// runtime (Node / Deno / Bun / edge / browser) with no fs read and no `node:module` import. Runs as the
// first half of the build script (see package.json).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const { version } = JSON.parse(readFileSync(resolve(here, "package.json"), "utf8"));
writeFileSync(
  resolve(here, "src/version.ts"),
  `// Generated by genversion.mjs at build — do not edit.\nexport const SDK_VERSION = ${JSON.stringify(version)};\n`,
);
console.log(`[sdk build] baked SDK_VERSION = ${version}`);
